/**
 * lib/aclBuilder.ts — Visual ACL policy generation from dashboard tags.
 *
 * The dashboard's node tags (lib/tags.ts) are cosmetic labels, not Headscale's
 * native `tag:` ACL mechanism (which requires `tagOwners` + a node advertising
 * the tag at registration). To make a "tag-based" builder actually enforce
 * anything, we resolve each dashboard tag to its members' current mesh IPv4
 * addresses and inline those directly into the generated HuJSON `src`/`dst`
 * arrays — a real, working policy, at the cost of needing to be regenerated
 * whenever tagged nodes are added/removed (their IPs otherwise go stale).
 *
 * Apply merges a marked block into the existing policy so hand-written ACLs,
 * groups, and DNS extra records are not wiped.
 */

export interface TagGroupNode {
  id: string;
  name: string;
  ip: string | null;
}

export interface TagGroup {
  tag: string;
  nodes: TagGroupNode[];
}

export interface AclRule {
  id: string;
  srcTag: string;
  dstTag: string;
  ports: string; // '*' or comma-separated port list, e.g. '22,443'
}

export const BUILDER_BEGIN = '// BEGIN LAVAMESH-BUILDER';
export const BUILDER_END = '// END LAVAMESH-BUILDER';

export async function getTagGroups(): Promise<TagGroup[]> {
  const { getNodes } = await import('./headscale');
  const { getTagsForNodes } = await import('./tags');
  const nodes = await getNodes();
  const nodeIds: string[] = nodes.map((n: any) => String(n.id));
  const tagsByNode = await getTagsForNodes(nodeIds);

  const groups = new Map<string, TagGroupNode[]>();
  for (const n of nodes) {
    const tags = tagsByNode[String(n.id)] || [];
    if (tags.length === 0) continue;
    const ip: string | null = n.ipAddresses?.find((addr: string) => !addr.includes(':')) ?? null;
    for (const tag of tags) {
      if (!groups.has(tag)) groups.set(tag, []);
      groups.get(tag)!.push({ id: String(n.id), name: n.givenName || n.name, ip });
    }
  }

  return [...groups.entries()]
    .map(([tag, groupNodes]) => ({ tag, nodes: groupNodes }))
    .sort((a, b) => a.tag.localeCompare(b.tag));
}

const PORTS_RE = /^(\*|\d+(,\d+)*)$/;

export function validateRule(rule: AclRule, groups: TagGroup[]): string | null {
  if (!rule.srcTag || !rule.dstTag) return 'Pick a source and destination tag.';
  const src = groups.find(g => g.tag === rule.srcTag);
  const dst = groups.find(g => g.tag === rule.dstTag);
  if (!src?.nodes.some(n => n.ip)) return `Tag "${rule.srcTag}" has no nodes with a mesh IPv4 address.`;
  if (!dst?.nodes.some(n => n.ip)) return `Tag "${rule.dstTag}" has no nodes with a mesh IPv4 address.`;
  if (!PORTS_RE.test(rule.ports.trim())) return 'Ports must be "*" or a comma-separated list, e.g. "22,443".';
  return null;
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function builderEntries(rules: AclRule[], groups: TagGroup[]): string[] {
  const findIps = (tag: string) =>
    (groups.find(g => g.tag === tag)?.nodes || []).map(n => n.ip).filter((ip): ip is string => !!ip);

  return rules.map(rule => {
    const srcIps = findIps(rule.srcTag);
    const dstIps = findIps(rule.dstTag);
    const port = rule.ports.trim() || '*';
    const src = srcIps.map(ip => `"${ip}/32"`).join(', ');
    const dst = dstIps.map(ip => `"${ip}/32:${port}"`).join(', ');
    return [
      `    // tag:${rule.srcTag} \u2192 tag:${rule.dstTag} (${port === '*' ? 'all ports' : 'port ' + port})`,
      `    { "action": "accept", "src": [${src}], "dst": [${dst}] }`,
    ].join('\n');
  });
}

function builderBlock(rules: AclRule[], groups: TagGroup[]): string {
  const entries = builderEntries(rules, groups);
  return [`    ${BUILDER_BEGIN}`, entries.join(',\n'), `    ${BUILDER_END}`].join('\n');
}

export function extractBuilderBlock(policy: string): string | null {
  const re = new RegExp(`${escapeRe(BUILDER_BEGIN)}[\\s\\S]*?${escapeRe(BUILDER_END)}`);
  const m = policy.match(re);
  return m ? m[0] : null;
}

/** Standalone policy file used when there is no existing ACL to merge into. */
export function compilePolicy(rules: AclRule[], groups: TagGroup[]): string {
  return [
    '{',
    '  // Generated by the Visual ACL Builder from LavaMesh dashboard tags.',
    '  // Re-applying the builder updates only the marked block — other acls stay.',
    '  "acls": [',
    builderBlock(rules, groups),
    '  ]',
    '}',
  ].join('\n');
}

function findMatchingBracket(s: string, openIdx: number): number {
  let depth = 0;
  let inStr = false;
  let esc = false;
  for (let i = openIdx; i < s.length; i++) {
    const c = s[i];
    if (inStr) {
      if (esc) { esc = false; continue; }
      if (c === '\\') { esc = true; continue; }
      if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') { inStr = true; continue; }
    if (c === '[') depth++;
    if (c === ']') {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
}

/**
 * Splice the builder's marked ACL block into an existing policy without
 * replacing groups, hosts, or hand-written acls.
 */
export function mergeBuilderIntoExisting(existing: string, compiled: string): string {
  const newBlock = extractBuilderBlock(compiled);
  if (!newBlock) return compiled;

  if (existing.includes(BUILDER_BEGIN) && existing.includes(BUILDER_END)) {
    return existing.replace(
      new RegExp(`${escapeRe(BUILDER_BEGIN)}[\\s\\S]*?${escapeRe(BUILDER_END)}`),
      newBlock,
    );
  }

  const aclsIdx = existing.search(/"acls"\s*:\s*\[/);
  if (aclsIdx === -1) return compiled;

  const openBracket = existing.indexOf('[', aclsIdx);
  const close = findMatchingBracket(existing, openBracket);
  if (close < 0) return compiled;

  const inner = existing.slice(openBracket + 1, close).trim();
  const glue = inner.length === 0 ? '\n' : (inner.endsWith(',') ? '\n' : ',\n');
  return existing.slice(0, close) + glue + newBlock + '\n  ' + existing.slice(close);
}
