/**
 * lib/aclBuilder.ts — Visual ACL policy generation from dashboard tags.
 *
 * The dashboard's node tags (lib/tags.ts) are cosmetic labels, not Headscale's
 * native `tag:` ACL mechanism (which requires `tagOwners` + a node advertising
 * the tag at registration). To make a "tag-based" builder actually enforce
 * anything, we resolve each dashboard tag to its members' current mesh IPv4
 * addresses and inline those directly into the generated HuJSON `src`/`dst`
 * arrays — a real, working policy, at the cost of needing to be regenerated
 * whenever tagged nodes are added/removed (their IPs otherwise go stale).
 */

import { getNodes } from './headscale';
import { getTagsForNodes } from './tags';

export interface TagGroupNode {
  id: string;
  name: string;
  ip: string | null;
}

export interface TagGroup {
  tag: string;
  nodes: TagGroupNode[];
}

export interface AclRule {
  id: string;
  srcTag: string;
  dstTag: string;
  ports: string; // '*' or comma-separated port list, e.g. '22,443'
}

export async function getTagGroups(): Promise<TagGroup[]> {
  const nodes = await getNodes();
  const nodeIds: string[] = nodes.map((n: any) => String(n.id));
  const tagsByNode = await getTagsForNodes(nodeIds);

  const groups = new Map<string, TagGroupNode[]>();
  for (const n of nodes) {
    const tags = tagsByNode[String(n.id)] || [];
    if (tags.length === 0) continue;
    const ip: string | null = n.ipAddresses?.find((addr: string) => !addr.includes(':')) ?? null;
    for (const tag of tags) {
      if (!groups.has(tag)) groups.set(tag, []);
      groups.get(tag)!.push({ id: String(n.id), name: n.givenName || n.name, ip });
    }
  }

  return [...groups.entries()]
    .map(([tag, groupNodes]) => ({ tag, nodes: groupNodes }))
    .sort((a, b) => a.tag.localeCompare(b.tag));
}

const PORTS_RE = /^(\*|\d+(,\d+)*)$/;

export function validateRule(rule: AclRule, groups: TagGroup[]): string | null {
  if (!rule.srcTag || !rule.dstTag) return 'Pick a source and destination tag.';
  const src = groups.find(g => g.tag === rule.srcTag);
  const dst = groups.find(g => g.tag === rule.dstTag);
  if (!src?.nodes.some(n => n.ip)) return `Tag "${rule.srcTag}" has no nodes with a mesh IPv4 address.`;
  if (!dst?.nodes.some(n => n.ip)) return `Tag "${rule.dstTag}" has no nodes with a mesh IPv4 address.`;
  if (!PORTS_RE.test(rule.ports.trim())) return 'Ports must be "*" or a comma-separated list, e.g. "22,443".';
  return null;
}

export function compilePolicy(rules: AclRule[], groups: TagGroup[]): string {
  const findIps = (tag: string) =>
    (groups.find(g => g.tag === tag)?.nodes || []).map(n => n.ip).filter((ip): ip is string => !!ip);

  const entries = rules.map(rule => {
    const srcIps = findIps(rule.srcTag);
    const dstIps = findIps(rule.dstTag);
    const port = rule.ports.trim() || '*';
    const src = srcIps.map(ip => `"${ip}/32"`).join(', ');
    const dst = dstIps.map(ip => `"${ip}/32:${port}"`).join(', ');
    return [
      `    // tag:${rule.srcTag} \u2192 tag:${rule.dstTag} (${port === '*' ? 'all ports' : 'port ' + port})`,
      `    { "action": "accept", "src": [${src}], "dst": [${dst}] }`,
    ].join('\n');
  });

  return [
    '{',
    '  // Generated by the Visual ACL Builder from LavaMesh dashboard tags.',
    '  // You can hand-edit this — regenerating from the builder will overwrite it.',
    '  "acls": [',
    entries.join(',\n'),
    '  ]',
    '}',
  ].join('\n');
}
