/**
 * lib/headscaleConfig.ts — Generates the two files injected into a Cloud
 * tenant's Fly Machine at boot (see lib/fly.ts `createMachine`'s `files`).
 *
 * 1. config.yaml   — a real Headscale 0.22.x config, not a placeholder.
 * 2. bootstrap.sh   — overrides the image's entrypoint so we can start
 *    Headscale, wait for it to come up, mint an admin API key via the
 *    `headscale` CLI (already inside the image), and phone that key home to
 *    our callback endpoint before handing off to `headscale serve` as the
 *    long-running foreground process.
 *
 * Why a bootstrap script instead of just `headscale serve`: the Headscale
 * HTTP/gRPC API requires an API key to authenticate, and the only way to
 * mint the first one is the local CLI inside the container — there's no
 * unauthenticated "create my first key" endpoint. Running it once at boot
 * and POSTing the result to our own callback (see
 * app/api/provision/callback/route.ts) is the standard bootstrap pattern
 * for headless Headscale deployments.
 *
 * Known limitation (first iteration): this assumes the `headscale/headscale`
 * Alpine-based image has `wget` (BusyBox) available for the callback POST,
 * which it does as of the images this was tested against. If Headscale ever
 * ships a distroless image, swap the callback call for a tiny sidecar or a
 * custom wrapper image instead of relying on `wget`.
 */

export function buildHeadscaleConfig(opts: { serverUrl: string; baseDomain: string }): string {
  return `# Generated by LavaMesh Cloud provisioning — do not edit by hand.
server_url: ${opts.serverUrl}
listen_addr: 0.0.0.0:8080
metrics_listen_addr: 127.0.0.1:9090
grpc_listen_addr: 127.0.0.1:50443
grpc_allow_insecure: false

noise:
  private_key_path: /data/noise_private.key

prefixes:
  v4: 100.64.0.0/10
  v6: fd7a:115c:a1e0::/48
  allocation: sequential

derp:
  server:
    enabled: false
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  auto_update_enabled: true
  update_frequency: 24h

disable_check_updates: true
ephemeral_node_inactivity_timeout: 30m

database:
  type: sqlite
  sqlite:
    path: /data/db.sqlite

log:
  format: text
  level: info

dns:
  magic_dns: true
  base_domain: ${opts.baseDomain}
  nameservers:
    global:
      - 1.1.1.1
      - 8.8.8.8
  search_domains: []

unix_socket: /var/run/headscale/headscale.sock
unix_socket_permission: "0770"
`;
}

export function buildBootstrapScript(opts: { tenantId: string; callbackUrl: string; provisioningSecret: string }): string {
  // Runs as PID 1 (see lib/fly.ts entrypoint override). Starts headscale in the
  // background, polls its /health endpoint, mints a long-lived API key, phones
  // it home, then execs into `headscale serve` so it becomes the container's
  // foreground process (keeping restart/health-check semantics correct).
  return `#!/bin/sh
set -e
mkdir -p /var/run/headscale /data

headscale serve &
HS_PID=$!

echo "[bootstrap] waiting for headscale to become healthy..."
i=0
until wget -q -O- http://127.0.0.1:8080/health >/dev/null 2>&1; do
  i=$((i+1))
  if [ "$i" -gt 60 ]; then
    echo "[bootstrap] headscale never became healthy after 60s, giving up on key creation"
    wait "$HS_PID"
    exit 1
  fi
  sleep 1
done
echo "[bootstrap] headscale is healthy"

headscale users create admin 2>/dev/null || true
API_KEY=$(headscale apikeys create --expiration 87600h 2>/dev/null | tail -n 1)

if [ -n "$API_KEY" ]; then
  echo "[bootstrap] created api key, notifying provisioning callback"
  printf '{"tenantId":"%s","apiKey":"%s"}' "${opts.tenantId}" "$API_KEY" > /tmp/callback.json
  wget -q -O- \\
    --header="Content-Type: application/json" \\
    --header="Authorization: Bearer ${opts.provisioningSecret}" \\
    --post-file=/tmp/callback.json \\
    "${opts.callbackUrl}" >/dev/null 2>&1 || echo "[bootstrap] callback failed, cron will retry via health check"
  rm -f /tmp/callback.json
else
  echo "[bootstrap] apikey creation failed or already exists, skipping callback"
fi

wait "$HS_PID"
`;
}
